services:
  app:
    image: php:8.2-apache
    container_name: fin_app
    volumes:
      - ./app:/var/www/html
      - ./data:/app_data
    expose:
      - "80"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: fin_caddy
    ports:
      - "8090:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./app:/var/www/html         # <-- ESSENCIAL para servir arquivos!
      - caddy_data:/caddy_data
      - caddy_config:/config
    depends_on:
      - app
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
